In [1]:
import torch

In [2]:
# jupyter notebook shift+tab: detail view e.g. parameters info, type, and so on.

In [3]:
x = torch.ones(2, 2, requires_grad=True)
x2 = torch.ones(2, 2)
x3 = torch.ones(1, requires_grad=True)
print(x)
print(x2)
print(x3)
y = x + 2 # grad_fn is attached to only when any operand's requires_grad=True for calculating the derivatives. 
y2 = x2 + 2
y3 = x3 + 2
print(y)
print(y2)
print(y3)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])
tensor([1.], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[3., 3.],
        [3., 3.]])
tensor([3.], grad_fn=<AddBackward0>)


In [4]:
print(y.requires_grad)
print(y2.requires_grad)
print(y3.requires_grad)

True
False
True


In [5]:
# x3.grad.data.zero_()

In [6]:
y3.backward()
print(x3.grad)
# On graph x -> y -> l, calling y.backward(dl/dy) propagate dl/dx to x.

tensor([1.])


In [7]:
print(x.size())
print(x.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [20]:
a = torch.tensor([[1.,2.,3.], [4.,5.,6.]], requires_grad=True)
b = torch.zeros(2, 3)
y = torch.sum(a+b)
z = 2 * y
print(a, a.requires_grad, a.grad)
print(b, b.requires_grad, b.grad)
print(y, y.requires_grad, y.grad)
print(z, z.requires_grad, z.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True) True None
tensor([[0., 0., 0.],
        [0., 0., 0.]]) False None
tensor(21., grad_fn=<SumBackward0>) True None
tensor(42., grad_fn=<MulBackward0>) True None


In [26]:
c = torch.randn(2,3)
d = torch.randn(2,3)
e = torch.sum(c + d)
print(e, e.requires_grad, e.grad)
e.requires_grad_()
print(e, e.requires_grad, e.grad)
e.backward()
print(e, e.requires_grad, e.grad)

tensor(9.8929) False None
tensor(9.8929, requires_grad=True) True None
tensor(9.8929, requires_grad=True) True tensor(1.)


In [27]:
y.detach_()
print(a, a.requires_grad, a.grad)
print(b, b.requires_grad, b.grad)
print(y, y.requires_grad, y.grad)
print(z, z.requires_grad, z.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True) True None
tensor([[0., 0., 0.],
        [0., 0., 0.]]) False None
tensor(21.) False None
tensor(42., grad_fn=<MulBackward0>) True None


In [28]:
z.backward()
print(a, a.requires_grad, a.grad)
print(b, b.requires_grad, b.grad)
print(y, y.requires_grad, y.grad)
print(z, z.requires_grad, z.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True) True tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]]) False None
tensor(21.) False None
tensor(42., grad_fn=<MulBackward0>) True None


In [31]:
a = torch.tensor([[1.,2.,3.], [4.,5.,6.]], requires_grad=True)
b = torch.zeros(2, 3)
y = torch.sum(a+b)
y.detach_()
z = 2 * y
z.requires_grad_()
print(a, a.requires_grad, a.grad)
print(b, b.requires_grad, b.grad)
print(y, y.requires_grad, y.grad)
print(z, z.requires_grad, z.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True) True None
tensor([[0., 0., 0.],
        [0., 0., 0.]]) False None
tensor(21.) False None
tensor(42., requires_grad=True) True None


In [32]:
z.backward()
print(a, a.requires_grad, a.grad)
print(b, b.requires_grad, b.grad)
print(y, y.requires_grad, y.grad)
print(z, z.requires_grad, z.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True) True None
tensor([[0., 0., 0.],
        [0., 0., 0.]]) False None
tensor(21.) False None
tensor(42., requires_grad=True) True tensor(1.)


In [34]:
q = torch.tensor([1.], requires_grad=True)
print(q.requires_grad)
q.detach_()
print(q.requires_grad)
qq = torch.tensor([1.], requires_grad=True)
print(qq.requires_grad)
qq.grad.detach_()
print(qq.requires_grad)

True
False
True


AttributeError: 'NoneType' object has no attribute 'detach_'

In [35]:
z.grad.requires_grad

False

In [36]:
a = torch.tensor([[1.,2.,3.], [4.,5.,6.]], requires_grad=True)
b = torch.zeros(2, 3)
y = torch.sum(a+b)
z = 2 * y
print(a, a.requires_grad, a.grad)
print(b, b.requires_grad, b.grad)
print(y, y.requires_grad, y.grad)
print(z, z.requires_grad, z.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True) True None
tensor([[0., 0., 0.],
        [0., 0., 0.]]) False None
tensor(21., grad_fn=<SumBackward0>) True None
tensor(42., grad_fn=<MulBackward0>) True None


In [39]:
z.backward()
print(a, a.requires_grad, a.grad)
print(b, b.requires_grad, b.grad)
print(y, y.requires_grad, y.grad)  # y,z의 gradient: 역전파를 위해 추적은 하되, 매개변수 업데이트에 쓰이는 애들이 아니니까 따로 저장하지 않음
print(z, z.requires_grad, z.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True) True tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]]) False None
tensor(21., grad_fn=<SumBackward0>) True None
tensor(42., grad_fn=<MulBackward0>) True None


AttributeError: 'NoneType' object has no attribute 'requires_grad'